name: Deploy to Server

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Setup GitHub SSH (for repo checkout)
      - name: Setup GitHub SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Debug GitHub SSH
      - name: Debug SSH to GitHub
        run: ssh -i ~/.ssh/id_ed25519 -T git@github.com

      # Checkout private repo
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Setup server SSH
      - name: Setup Server SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_server
          chmod 600 ~/.ssh/id_server
          ssh-keyscan -H 165.22.218.65 >> ~/.ssh/known_hosts

      # Debug server SSH
      - name: Debug SSH to Server
        run: ssh -i ~/.ssh/id_server -o StrictHostKeyChecking=no root@165.22.218.65 "echo 'SSH to server works'"

      # Deploy to server
      - name: Deploy to Server
        run: ssh -i ~/.ssh/id_server -o StrictHostKeyChecking=no root@165.22.218.65 'bash -s' < ./deploy.sh




